### ISSUE TITLE
need to include exception for Bathy_depth

### ISSUE THREAD

**Issue by oj713** [BigelowLab/brickman#2]
This code adds a "d" prefix to any input variable names -- however, "Bathy_depth" should instead be left unchanged. 

https://github.com/BigelowLab/brickman/blob/01136f2a28962d96fd5d5c13d362cb5e1656da98/R/io.R#L31

**Comment by btupper** [comment]
Appears to be fixed for good with https://github.com/BigelowLab/brickman/commit/2ec7f8f2c3dcd142e9f54c214e0252c6ec034c46 (fingers crossed)

I'll leave this open - test it out.  If it works then go ahead and close this issue.
