### ISSUE TITLE
need to include exception for Bathy_depth

### ISSUE THREAD

**Issue by oj713** [BigelowLab/brickman#3]
This code adds an "_ann" suffix to all variables when processing layers -- however, Bathy_depth needs to be excluded. 

https://github.com/BigelowLab/brickman/blob/01136f2a28962d96fd5d5c13d362cb5e1656da98/R/io.R#L8`

`    x <- suppressWarnings(stars::read_stars(filename,
                           sub = paste0(vars, "_ann"),
                           curvilinear = c("nav_lon", "nav_lat"),
                           quiet = !verbose)) |>
      rlang::set_names(paste0(vars, "_ann"))`

**Comment by btupper** [comment]
Appears to be fixed for good with https://github.com/BigelowLab/brickman/commit/2ec7f8f2c3dcd142e9f54c214e0252c6ec034c46 (fingers crossed)
