### ISSUE TITLE
Monthly data not being read correctly 

### ISSUE THREAD

**Issue by oj713** [BigelowLab/brickman#5]
The commented out function in the monthly section of extract_points needs to be uncommented - the "simplified" version it was replaced with isn't working correctly and is returning a single value instead of the 12 monthly values

https://github.com/BigelowLab/brickman/blob/f279b8e799d47b389aa00cf484fd9f356395db96/R/extract.R#L71

Example script to replicate the problem: 
```
library(brickman)
# retrieving example monthly column
X <- ncdf4::nc_open(compose_filename(scenario="PRESENT"))
V <- ncdf4::ncvar_get(X, "SST")

# using first entry in V as example
current_returned <- V[1]
commented_out_returned <- V[1, 1, ]

length(current_returned) # 1 - wrong!
length(commented_out_returned) # 12 - right!
```

**Comment by btupper** [comment]
Sorry, I bungled the issues.  But the problem is fixed!
